### ISSUE TITLE
Layers not showing up

### ISSUE THREAD

**Issue by jaraine** [doug-m/CollectorAuroraTesting#224]
### Issue

For map IWSCycle2CollectorBetaTest(which is shared with you guys now), the navigation lines don’t show up and it gives a warning triangle in the layers menu that the field already exists.  This feature is not used to collect data, it is used for reference and to collect related data, such as which species were collected along a transect and when the line was last surveyed.

### Expected Behavior
All layers should show up.  This works in Collector Classic.

### Map and Credentials

* Group Name: PohakuloaTrainingAreaESRISupport
* Map Name: IWSCycle2CollectorBetaTest

### Steps to Reproduce
Open map, and see which layers show up

### Device Information
* Device: Moto G5Plus and Moto G7Power
* OS Version: Android Version 6 and Version 9

**Comment by Kevin-GIS** [comment]
Hi @jaraine 

I was able to reproduce the issue with `NavigationLines` failing to load in the map.

When reviewing the JSON for the `NavigationLines` layer for the hosted feature service in ArcGIS Online, I noticed that the 4 editor tracking fields (CreationDate,Creator,EditDate,Editor) have their `editable` property set to `true` instead of `false`. This is likely why the layer is failing to load due to this configuration issue. Because editor tracking fields are system controlled, they aren't considered to be editable like other user-defined fields are as these fields get programmatically updated. 

<details>
<summary>Editor tracking fields for NavigationLines</summary>

![c1](https://user-images.githubusercontent.com/24723464/62723320-4b07a980-b9c5-11e9-9b14-7161852fb6c3.PNG)

</details>

There is another set of editor tracking fields that aren't being used (CreationDate_1,Creator_1,EditDate_1,Editor_1) that do have the `editable` property set to `false`. 

I am able to determine which fields are being used for Editor Tracking at the top of the JSON for the `NavigationLines` layer:
<details>
<summary>Set editor tracking fields for NavigationLines</summary>

![c3](https://user-images.githubusercontent.com/24723464/62723467-a043bb00-b9c5-11e9-8d74-32a2b38604a8.PNG)

</details>

When I compared the editor tracking fields with other layers in this service, such as `SpeciesListTransects`. those editor tracking fields are correct with `editable` set to `false`. Therefore it's just `NavigationLines` that has this issue with those fields. 

- Would you be able to provide any additional information regarding how the CreationDate, Creator, EditDate, Editor fields were originally created in `NavigationLines` and why there might be the second set of fields with '_1' at the end? 
- Were these fields already in the local copy of this data prior to it being published to ArcGIS Online?

**Comment by jaraine** [comment]
Hi Kevin

Thanks for looking into this and getting back to me.  What you said makes
sense.

To answer your questions, I think that this is a product of creating this
product early in our use of ArcGIS Online and Collector, when it was harder
to make changes to domains and fields.   I think that we probably created
the hosted feature layer, and then we had to make changes to the structure
of the hosted feature layer.  I think we exported it to a FGDB, made the
changes and then rehosted the feature layer.  I think in the process we
somehow created those fields twice(Creator, CreationDate, Editor and
EditorDate are from the original dataset and the ones with _1 are what
happened when we published again).  I think it is probably a symptom of us
learning this on the fly.

I think they were in the local copy because it was exported from a hosted
feature layer.

We do not need those fields, as this is a layer that should not be edited
by the user, they are only addiing related records.  Would you say best
practice is to delete the ones with the editable property set incorrectly?

Thanks again for your help.

Jonathan

**Comment by Kevin-GIS** [comment]
Hi @jaraine 

Thank you for that information. I performed some testing by publishing from Pro and ArcMap and I cannot reproduce this issue with how the Editor Tracking fields were set to be editable in the feature service. Even when I enabled editor tracking for the feature class inside the file geodatabase where I had chosen editable fields, upon publishing those fields were no longer editable. Therefore the publishing process seems to have handled that and ensured they were no longer editable since they were being used for editor tracking. Therefore I am not sure how the `NavigationLines` layer had gotten into this state, but as you explained above perhaps it was due to that particular workflow that caused this anomaly to occur. 

The only way that I am able to reproduce this issue is to disable editor tracking for the service and then edit the JSON for those fields and change `false` to `true` and then re-enable editor tracking. When I open this map in Collector, that layer fails to load with the same error as you're seeing. In general you should never need to edit the JSON of a feature service, as it could lead to problems, however this was just my attempt to force the issue to happen. 

Therefore here are a few options you can try:
- Try deleting those 4 problematic fields from `NavigationLines`. You might need to first disable editor tracking for the service and then re-enable it once they've been deleted. You may also find that you cannot delete those fields and my assumption is that because they were used for editor tracking they cannot be deleted. However because these fields are editable, you might be able to. 
- If you cannot delete those fields, perhaps you can try editing the JSON through the REST admin page and changing them from `true` back to `false`. This would be performed via the `updateDefinition`. In order to do this, you might need to disable editor tracking on the service first. 
- You could also try exporting to a file gdb > remove the fields > republish to a new service with editor tracking enabled.

Because we're dealing with Editor Tracking fields which are controlled by the software, the steps that are available to resolve these types of issues can be challenging mainly because there is less available functionality to interact with those fields when compared with user-defined fields. 

Please let me know if you have any questions.

Thank you.

**Comment by Kevin-GIS** [comment]
Hi @jaraine 

I just wanted to follow-up with you regarding the last bit of information I shared. I recently tested with the map above and the layers are loading. Therefore it appears you were able to successfully delete those other editor tracking fields from the service for the `NavigationLines` layer?

I also noticed a different issue where `NavigationLines` still doesn't display in the map. I see this on both iOS and Android. Are you seeing the same issue?

Thanks
-Kevin
